# Generated by Django 2.2.1 on 2019-11-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_pay', models.IntegerField(default=0)),
                ('paytm', models.IntegerField(default=0)),
                ('phone', models.IntegerField(default=0)),
                ('card_holder_name', models.CharField(max_length=60)),
                ('card_no', models.CharField(max_length=21)),
                ('product_id', models.IntegerField(default=0)),
                ('master_user_id', models.IntegerField(default=0)),
                ('card_day', models.IntegerField(default=0)),
                ('card_month', models.IntegerField(default=0)),
                ('payment_type', models.CharField(max_length=20)),
            ],
        ),
    ]
