# Generated by Django 2.2.1 on 2019-09-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=60)),
                ('zipcode', models.IntegerField(default=0)),
                ('phone', models.IntegerField(default=0)),
                ('payment_type', models.CharField(max_length=20)),
            ],
        ),
    ]
