# Generated by Django 2.2.1 on 2019-11-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20191112_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paytm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_pay',
            field=models.IntegerField(default=0),
        ),
    ]
