# Generated by Django 2.2.1 on 2019-09-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_holder_name',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='card_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_no',
            field=models.IntegerField(default=0),
        ),
    ]
