# Generated by Django 2.2.1 on 2019-10-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20190920_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='book_id',
            field=models.IntegerField(default=0),
        ),
    ]
