# Generated by Django 2.2.1 on 2019-12-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20191113_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_no',
            field=models.CharField(default=0, max_length=21),
        ),
    ]
