# Generated by Django 2.2.1 on 2019-12-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20191202_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_no',
            field=models.CharField(max_length=21),
        ),
    ]
