# Generated by Django 2.2.1 on 2019-10-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_payment_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_day',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_holder_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_month',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='card_name',
            field=models.CharField(default='Rajshekhar Rakshit', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_no',
            field=models.CharField(max_length=20),
        ),
    ]
