# Generated by Django 2.2.1 on 2019-12-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20191214_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_holder_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_no',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='payment',
            name='master_user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paytm',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_pay',
            field=models.CharField(max_length=11),
        ),
    ]
