# Generated by Django 2.2.1 on 2019-10-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20191002_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='card_name',
            new_name='card_holder_name',
        ),
        migrations.AddField(
            model_name='payment',
            name='card_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_month',
            field=models.IntegerField(default=0),
        ),
    ]
