# Generated by Django 2.2.1 on 2019-12-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20191214_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_holder_name',
            field=models.CharField(default=0, max_length=60),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_no',
            field=models.CharField(default=0, max_length=21),
        ),
        migrations.AlterField(
            model_name='payment',
            name='master_user_id',
            field=models.IntegerField(default=0),
        ),
    ]
