# Generated by Django 2.2.1 on 2019-12-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20191214_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_holder_name',
            field=models.CharField(default='None', max_length=60),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_no',
            field=models.CharField(default='None', max_length=21),
        ),
    ]
