# Generated by Django 2.2.1 on 2019-10-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_payment_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='current_user_id',
            field=models.IntegerField(default=0),
        ),
    ]
