# Generated by Django 2.2.1 on 2019-12-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20191214_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paytm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_pay',
            field=models.IntegerField(default=0),
        ),
    ]
