# Generated by Django 2.2.1 on 2019-10-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_payment_current_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='current_user_id',
            new_name='master_user_id',
        ),
    ]
