# Generated by Django 2.2.1 on 2019-12-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_auto_20191214_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='To_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_to_order_id', models.IntegerField()),
            ],
        ),
    ]
