# Generated by Django 2.2.1 on 2019-08-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('pages', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('desc', models.TextField()),
                ('price', models.IntegerField(default=1)),
            ],
        ),
    ]
