# Generated by Django 2.2.1 on 2019-08-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='desc',
        ),
        migrations.AddField(
            model_name='books',
            name='language',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
