# Generated by Django 2.2.1 on 2019-08-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190813_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='ISBN',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
