# Generated by Django 2.2.1 on 2019-08-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='edition',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
