# Generated by Django 2.2.1 on 2019-08-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='monthly_payment',
            field=models.IntegerField(default=1),
        ),
    ]
