# Generated by Django 2.2.1 on 2019-08-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_books_monthly_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='monthly_payment',
            field=models.IntegerField(default=0),
        ),
    ]
