# Generated by Django 2.2.1 on 2019-09-13 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20190814_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='title',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='books',
            name='monthly_payment',
        ),
    ]
