# Generated by Django 2.2.1 on 2019-09-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20190913_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='language',
            new_name='book_language',
        ),
    ]
