# Generated by Django 2.2.1 on 2019-09-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20190913_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='descreption',
            field=models.CharField(default='best book ever', max_length=300),
            preserve_default=False,
        ),
    ]
